site_name: Документация
theme:
  name: material
  features:
    - navigation.tabs
    - content.tabs
  palette:
    - scheme: default
      primary: indigo
    - scheme: slate
      primary: blue

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css