site_name: Документация
theme:
  name: material
  features:
    - navigation.tabs
    - content.tabs
    - navigation.top
    - search.highlight
  palette:
    - media: "(prefers-color-scheme: light)"  # Светлая тема
      scheme: default
      primary: teal
      toggle:
        icon: material/brightness-7
        name: Переключиться на темный режим
    - media: "(prefers-color-scheme: dark)"  # Темная тема
      scheme: slate
      primary: teal
      toggle:
        icon: material/brightness-4
        name: Переключиться на светлый режим

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tilde

extra_css:
  - stylesheets/extra.css


nav:
  - Главная: index.md
  - Функции:
    - Замечания: functions/Admonitions.md
    - Код: functions/Code.md
    - Форматы: functions/Formats.md
    - Таблицы: functions/Tables.md
    - Темы: functions/Themes.md
    - Директория:
      - Списки: functions/directory/Lists.md
      - Вкладки: functions/directory/Tabs.md
  - Проект:
    - Главная: project/index.md
    - О проекте: project/1about.md
    - Контакты: project/2contact.md
    - Начало работы:
      - Установка: project/installation.md
    - Конфигурация:
      - Основы: project/4configuration.md
      - Кастомизация: project/14customization.md
    - Разработка:
      - Вклад в проект: project/7contributing.md
      - История изменений: project/8changelog.md
    - Документация:
      - API документация: project/10api.md
      - Примеры: project/11examples.md
      - Продвинутые темы: project/12advanced.md
    - Публикация:
      - Публикация: project/13deployment.md
    - Поддержка:
      - Часто задаваемые вопросы: project/5faq.md
      - Решение проблем: project/6troubleshooting.md
    - Лицензия: project/9license.md
