# Пример структуры mkdocs.yml
site_name: Документация проекта
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - content.tabs
  palette:
    - scheme: default
      primary: indigo
      toggle:
        icon: material/weather-night
        name: Тёмная тема
    - scheme: slate
      primary: blue
      toggle:
        icon: material/weather-sunny
        name: Светлая тема

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist
  - pymdownx.tilde
  - pymdownx.emoji