name: Deploy Docs

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: |
          pip install mkdocs mkdocs-awesome-pages-plugin
          mkdocs build --site-dir site
      - name: Deploy to server
        uses: appleboy/ssh-action@latest
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            rm -rf /opt/docs*
            cp -r site/* /opt/docs/
