name: Deploy Docs

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: |
          pip install mkdocs mkdocs-awesome-pages-plugin mkdocs-material mkdocs-material-extensions
          mkdocs build --site-dir site
          ls -la
          pip list
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            mkdir -p /opt/docs
            rm -rf /opt/docs/*
            cp -r /home/runner/work/docs-meetup/docs-meetup/site/* /opt/docs/
            cp -r ./site/* /opt/docs/
